### ISSUE TITLE
Header To-Do

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/nanowrimo#4]
- [x] Add 'Navigate' to desktop version 
- [x] Add Logo - full version for desktop, acronym for mobile (acronym version nanowrimo - version in logo folder) 
- [x]  Remove text below the word donate on sidebar
- [x] Add {{site.baseurl}} to images 

(more to be added later)

**Comment by jamie-smith8** [comment]
done. 

{{site.baseurl}} still being tricky
